name: chr-node
website: https://chronara.net
source-code: https://github.com/CG-8663/chr-node
icon: snap/logo.png
base: core24
adopt-info: chr-node
summary: Chronara community lite node
description: |
  The Chronara Network is a decentralized community-driven P2P infrastructure network
  with multi-TLD support (.com, .net, .ai) and enhanced quality of service. Running a
  chr-node supports the community ecosystem, provides essential P2P infrastructure,
  and earns CHR token rewards for reliable service. Join the decentralized future! 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  chr-node:
    # See 'snapcraft plugins'
    plugin: make
    make-parameters: [-f snap/Makefile]
    source: .
    build-packages:
      - autoconf
      - automake
      - curl
      - g++
      - git
      - libc6
      - libgmp3-dev
      - libncurses-dev
      - libstdc++6
      - libtool
      - make
      - procps
      - snapd
      - unzip
      - wget
      - zlib1g-dev
    stage-packages:
      - mawk
      - libsigsegv2
      - libncurses6
      - libstdc++6
      - libc6
      - zlib1g
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags)"
      craftctl set grade="stable"

apps:
  service:
    command: bin/run start
    plugs: [network, network-bind]
    daemon: simple

  shell:
    command: bin/run elevated remote
    plugs: [network, network-bind]

  flush:
    command: bin/run elevated rpc ChronaraNode.Cmd.flush_cache
    plugs: [network, network-bind]

  info:
    command: bin/run rpc ChronaraNode.Cmd.status
    plugs: [network, network-bind]

  env:
    command: bin/run elevated rpc ChronaraNode.Cmd.env
    plugs: [network, network-bind]

