name: "CI"
on: ["push", "pull_request"]

jobs:
  test_and_build:
    name: "Build and lint"
    runs-on: "ubuntu-latest"
    steps:
    - name: Install deps
      run: sudo apt-get install -y libboost-dev libboost-system-dev

    - uses: actions/checkout@v1
    
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions
        version-type: strict

    - run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
        mix lint
        # mix test
